const fs = require('fs');
const file = fs.readFileSync("../sowpods.txt")
const words = file.toString().split('\n')

// PROBLEM: What are all of the words that have no E or A and are at least 15 letters long?

function solve() {
  let result = []
  for (let word of words) {
    if (!word.includes("E") && !word.includes("A") && word.length >= 15) {
      result.push(word)
    }
  }

  return result
}

console.log(solve())

// OUTPUT: [
//   'BIBLIOPHILISTIC', 'BLOODCURDLINGLY', 'BRONCHOSCOPISTS', 'CHRONOBIOLOGIST',
//   'CIRCUMLOCUTIONS', 'CIRCUMPOSITIONS', 'CIRCUMSCRIPTION', 'CIRCUMVOLUTIONS',
//   'CITRICULTURISTS', 'CONSCRIPTIONIST', 'CONSTITUTIONIST', 'CONSTRUCTIONISM',
//   'CONSTRUCTIONIST', 'CONSTRUCTIVISMS', 'CONSTRUCTIVISTS', 'CONTORTIONISTIC',
//   'CORTICOTROPHINS', 'COUNCILLORSHIPS', 'CROSSLINGUISTIC', 'CRYPTORCHIDISMS',
//   'CRYPTOSPORIDIUM', 'CRYPTOZOOLOGIST', 'DISCOMMODIOUSLY', 'DISCONTINUOUSLY',
//   'DISSOLUTIONISMS', 'DISSOLUTIONISTS', 'FLORICULTURISTS', 'GLUCOCORTICOIDS',
//   'HISTOPHYSIOLOGY', 'HORTICULTURISTS', 'HYDROBIOLOGISTS', 'HYDROSULPHUROUS',
//   'HYPOPHOSPHOROUS', 'HYPOTHYROIDISMS', 'HYSTRICOMORPHIC', 'IMMUNOBLOTTINGS',
//   'IMMUNODIFFUSION', 'IMMUNOGLOBULINS', 'INCONSPICUOUSLY', 'INCORRIGIBILITY',
//   'INDISSOLUBILITY', 'INFUNDIBULIFORM', 'INQUISITIONISTS', 'INSTRUCTORSHIPS',
//   'LITHONTHRYPTICS', 'LITHONTRIPTISTS', 'LITURGIOLOGISTS', 'MICROBIOLOGISTS',
//   'MICROCOMPUTINGS', 'MICROMORPHOLOGY', 'MICROPUBLISHING', 'MICROSPOROPHYLL',
//   'MISCONSTRUCTING', 'MISCONSTRUCTION', 'MISDISTRIBUTION', 'MISINSTRUCTIONS',
//   'MULTITUDINOUSLY', 'MYRISTICIVOROUS', 'NITROCHLOROFORM', 'NONCOGNITIVISMS',
//   'NONCONSTRUCTION', 'NONCONSUMPTIONS', 'NONCONTRIBUTORY', 'NONDISJUNCTIONS',
//   'NONPRODUCTIVITY', 'OBSTRUCTIONISMS', 'OBSTRUCTIONISTS', 'ODONTORHYNCHOUS',
//   'ONYCHOCRYPTOSIS', 'ORNITHORHYNCHUS', 'ORTHOPHOSPHORIC', 'PHOTOBIOLOGISTS',
//   'PHOTOCONDUCTING', 'PHOTOCONDUCTION', 'PHOTOCONDUCTORS', 'PHOTOFINISHINGS',
//   'PHOTOINDUCTIONS', 'PHOTOPRODUCTION', 'PISCICULTURISTS', 'POSTPRODUCTIONS',
//   'PROHIBITIONISMS', 'PROHIBITIONISTS', 'PROLOCUTORSHIPS', 'PROSTHODONTISTS',
//   'PROTISTOLOGISTS', 'PROTOPORPHYRINS', 'PROTOZOOLOGISTS', 'PSYCHOBIOLOGIST',
//   'PSYCHOLINGUISTS', 'PSYCHOPHYSICIST', 'PULCHRITUDINOUS', 'PYCNODYSOSTOSIS',
//   'PYKNODYSOSTOSIS', 'SHILLINGSWORTHS', 'SILVICULTURISTS', 'SOCIOBIOLOGISTS',
//   'SOCIOLINGUISTIC', 'STRONGYLOIDOSIS', 'THOROUGHGOINGLY', 'TRINITROTOLUOLS',
//   ... 5 more items
// ]